name: Test Install Script

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - test-install-script
      - test-wsl-arch
    paths:
      - '.github/workflows/test-install-script.yml'
      - 'install.sh'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/test-install-script.yml'
      - 'install.sh'

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, archlinux]
        include:
          - os: ubuntu-latest
            image: ubuntu:latest
          - os: ubuntu-22.04
            image: ubuntu:22.04
          - os: archlinux
            image: archlinux:latest

    name: ${{ matrix.os }}
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Make install.sh Executable
        run: chmod +x install.sh

      - name: Run Installation Script
        run: ./install.sh

  wsl:
    name: WSL
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up WSL2
        uses: vedantmgoyal9/setup-wsl2@main

      - name: Make install.sh Executable and Convert Line Endings
        run: |
          wsl sed -i 's/\r//' install.sh  
          wsl chmod +x install.sh          

      - name: Run Installation Script in WSL
        run: pwd && wsl bash ./install.sh  

  macos:
    name: MacOS Latest
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Make install.sh Executable
        run: chmod +x install.sh

      - name: Run Installation Script
        run: ./install.sh
